In [1]:
import pandas as pd
import numpy as np

Load Dataset

In [3]:
file_path = "D:/Code/project_code/Project/data/processed/master_dataset.csv"
df = pd.read_csv(file_path)

Hiển thị 5 dòng đầu tiên

In [4]:
df.head(5)

,course_id,course_title,price,level,subject,source_platform,enrollment_id,student_name,student_email,rating_score,completion_rate,enrollment_date,payment_method
0,1070968,Ultimate Investment Banking Course,200.0,All Levels,Business Finance,Udemy Courses,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1113822,Complete GST Course & Certification - Grow You...,75.0,All Levels,Business Finance,Udemy Courses,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1006314,Financial Modeling for Business Analysts and C...,45.0,Intermediate Level,Business Finance,Udemy Courses,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,95.0,All Levels,Business Finance,Udemy Courses,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1011058,How To Maximize Your Profits Trading Options,200.0,Intermediate Level,Business Finance,Udemy Courses,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Hiển thị 5 dòng cuối cùng

In [5]:
df.tail(5)

,course_id,course_title,price,level,subject,source_platform,enrollment_id,student_name,student_email,rating_score,completion_rate,enrollment_date,payment_method
12028,ONLINE166972,NaN,NaN,NaN,NaN,Online Courses,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12029,ONLINE914188,NaN,NaN,NaN,NaN,Online Courses,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12030,ONLINE654524,NaN,NaN,NaN,NaN,Online Courses,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12031,ONLINE136897,NaN,NaN,NaN,NaN,Online Courses,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12032,ONLINE155111,NaN,NaN,NaN,NaN,Online Courses,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Làm sạch văn bản

Xóa khoảng trắng thừa ở 2 đầu

In [12]:
text_cols = ['course_title', 'level', 'subject', 'source_platform', 'student_name', 'student_email', 'payment_method']
for col in text_cols: 
    df[col] = df[col].astype(str).str.strip()

Chuẩn hóa cột level (Viết hoa chữ cái đầu: beginner level -> Beginner Level)

In [13]:
df['level'] = df['level'].str.title()
df['level']

0                All Levels
1                All Levels
2        Intermediate Level
3                All Levels
4        Intermediate Level
                ...
12028                   NaN
12029                   NaN
12030                   NaN
12031                   NaN
12032                   NaN
Name: level, Length: 12033, dtype: str

Xử lý giá trị bị thiếu (missin value)

In [14]:
df.isna().sum()

course_id              0
course_title        3249
price               8027
level               7911
subject             5273
source_platform        0
enrollment_id      10530
student_name       10530
student_email      10530
rating_score       10530
completion_rate    10530
enrollment_date    10530
payment_method     10530
dtype: int64

In [ ]:
df["price"] = df['price'].fillna(df['price'].median())
df['level'] = df['level'].fillna(df['level'].mode()[0])
df['subject'] = df['subject'].fillna(df['subject'].mode()[0])
df['course_title'] = df['course_title'].fillna('Untitled Course')

df['enrollment_date'] = pd.to_datetime(df['enrollment_date'], errors='coerce')
df['rating_score'] = pd.to_numeric(df['rating_score'], errors='coerce')
df['completion_rate'] = pd.to_numeric(df['completion_rate'], errors='coerce')
df['enrollment_id'] = df['enrollment_id'].astype(str).replace('nan', np.nan)
df.isna().sum()

course_id              0
course_title           0
price                  0
level                  0
subject                0
source_platform        0
enrollment_id      10530
student_name       10530
student_email      10530
rating_score       10530
completion_rate    10530
enrollment_date    10530
payment_method     10530
dtype: int64

In [27]:
df['enrollment_year'] = df['enrollment_date'].dt.year
df['enrollment_month'] = df['enrollment_date'].dt.month
df['enrollment_day_name'] = df['enrollment_date'].dt.day_name()
df

,course_id,course_title,price,level,subject,source_platform,enrollment_id,student_name,student_email,rating_score,completion_rate,enrollment_date,payment_method,enrollment_year,enrollment_month,enrollment_day_name
0,1070968,Ultimate Investment Banking Course,200.0,All Levels,Business Finance,Udemy Courses,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
1,1113822,Complete GST Course & Certification - Grow You...,75.0,All Levels,Business Finance,Udemy Courses,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
2,1006314,Financial Modeling for Business Analysts and C...,45.0,Intermediate Level,Business Finance,Udemy Courses,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,95.0,All Levels,Business Finance,Udemy Courses,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
4,1011058,How To Maximize Your Profits Trading Options,200.0,Intermediate Level,Business Finance,Udemy Courses,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12028,ONLINE166972,Untitled Course,45.0,All Levels,Web Development,Online Courses,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
12029,ONLINE914188,Untitled Course,45.0,All Levels,Web Development,Online Courses,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
12030,ONLINE654524,Untitled Course,45.0,All Levels,Web Development,Online Courses,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
12031,ONLINE136897,Untitled Course,45.0,All Levels,Web Development,Online Courses,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
12032,ONLINE155111,Untitled Course,45.0,All Levels,Web Development,Online Courses,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN